services:
  web:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/local.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/app

  web_prod:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/production.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
