global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
       - targets: ['grafana:3100']

  - job_name: 'web_prod'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'db_prod'
    static_configs:
      - targets: ['localhost:5432']

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:8000']


