name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  COMPOSE_FILE: docker-compose.yml
  REPO_URL: emge1/allegro-clone-api
  REPO_BRANCH: main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH  }}

      - name: Start Services with Docker Compose
        run: |
          docker-compose down || true
          docker-compose up -d web

      - name: Run Tests
        run: |
          pytest --junitxml=test-reports/results.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml

      - name: Clean up Docker
        if: always()
        run: docker-compose down || true

      - name: Clean Workspace
        if: always()
        run: rm -rf *

      - name: Success Message
        if: success()
        run: echo "Pipeline successfully completed"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline unsuccessful"
