name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_URL: emge1/allegro-clone-api
  REPO_BRANCH: main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH  }}

      - name: Build Docker Image
        run: |
          docker build --build-arg REQUIREMENTS=requirements/local.txt -t ci-cd-image .

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ci-cd-image \
            sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              pytest --junitxml=test-reports/results.xml
            "

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml

      - name: Clean up Docker
        if: always()
        run: docker-compose down || true

      - name: Clean Workspace
        if: always()
        run: rm -rf *

      - name: Success Message
        if: success()
        run: echo "Pipeline successfully completed"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline unsuccessful"
