name: Security Scan with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_URL: emge1/allegro-clone-api
  REPO_BRANCH: main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH  }}

      - name: Build Docker Image
        run: |
          docker build --build-arg REQUIREMENTS=requirements/local.txt -t scan .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: scan
          severity: CRITICAL
          ignore-unfixed: true
          format: json
          output: trivy-report.json

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.json

      - name: Clean up Docker
        if: always()
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          docker network prune -f

      - name: Clean Workspace
        if: always()
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            scan \
            sh -c "rm -rf /workspace/*"

      - name: Success Message
        if: success()
        run: echo "Scan successfully completed"

      - name: Failure Message
        if: failure()
        run: echo "Scan unsuccessful"
